[package]
name = "archlinuxcn-packages"
version = "0.2.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
ansi-to-html = "0.1.3"
anyhow = "1.0.71"
bigdecimal = "0.3.1"
cached = "0.44.0"
chrono = "0.4.26"
deadpool-postgres = "0.10.5"
enum-display-derive = "0.1.1"
openssl = { version = "0.10.54", features = ["vendored"] }
pg_bigdecimal = "0.1.5"
postgres-types = { version = "0.2.5", features = ["derive"]}
sentry = "0.31.5"
sentry-actix = "0.31.4"
serde = { version = "1.0.164", features = ["derive"] }
tokio-postgres = { version = "0.7.8", features = ["with-chrono-0_4"]}
yaml-rust = "0.4.5"
