[package]
name = "archlinuxcn-packages"
version = "0.2.6"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
ansi-to-html = "0.1.3"
anyhow = "1.0.70"
bigdecimal = "0.3.0"
cached = "0.42.0"
chrono = "0.4.24"
deadpool-postgres = "0.10.5"
enum-display-derive = "0.1.1"
openssl = { version = "0.10.49", features = ["vendored"] }
pg_bigdecimal = "0.1.5"
postgres-types = { version = "0.2.5", features = ["derive"]}
sentry = "0.30.0"
sentry-actix = "0.30.0"
serde = { version = "1.0.159", features = ["derive"] }
tokio-postgres = { version = "0.7.8", features = ["with-chrono-0_4"]}
yaml-rust = "0.4.5"
