name: Release a new version

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - target: x86_64-unknown-linux-musl
            archive: tar.zst
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: 1.74.0
      - name: Install dependency
        run: |
          apt update
          apt install -y --no-install-recommends pkg-config libssl-dev
      - name: Compile and release
        uses: rust-build/rust-build.action@v1.4.4
        env:
          GITHUB_TOKEN: ${{ secrets.IMLONGHAO_BOT_TOKEN }}
        with:
          RUSTTARGET: ${{ matrix.target }}
          ARCHIVE_TYPES: ${{ matrix.archive }}
