name: Release a new version

on:
  push:
    tags:
      - '*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup rust
        uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: 1.74.0
          targets: x86_64-unknown-linux-musl
      - name: Compile
        run: cargo build --release --locked --all-features --target x86_64-unknown-linux-musl
      - name: Release
        uses: https://gitea.com/actions/release-action@main
        with:
          files: |-
            target/x86_64-unknown-linux-musl/release/archlinuxcn-packages
          api_key: ${{ secrets.IMLONGHAO_BOT_TOKEN }}
